# Generated by Django 4.1.3 on 2022-11-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
